## 1. Import Necessary Libraries

In [ ]:
import re
import string
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

### 2. Import the Dataset

In [ ]:
raw_data = pd.read_csv("/content/Raw_Property.csv")

In [ ]:
raw_data.head(10)

,Property_Name,Location,Price,Rate_SqFt,Area_Tpye,Bedroom,Bathroom,Floor_No,Property_Age,Availability
0,Omkar Alta Monte,"W.E.Highway, Malad East, Mumbai",5 Crore,"17,241",Super Built up area 2900(269.42 sq.m.)Built Up...,3,4,14th,0 to 1 Year Old,Ready to move
1,T Bhimjyani Neelkanth Woods,"Manpada, Thane, Mumbai",2.4 Crore,"12,631",Super Built up area 1900(176.52 sq.m.)Built Up...,3,3,8th,1 to 5 Year Old,Ready to move Property
2,Legend 1 Pramila Nagar,"Dahisar West, Mumbai",95 Lac,"15,966",Super Built up area 595(55.28 sq.m.),1,2,3rd,10+ Year Old,Ready to move
3,Unnamed Property,"Vidyavihar West, Vidyavihar West, Central Mumb...",3.75 Crore,"25,862",Built Up area: 1450 (134.71 sq.m.),3,3,1st,5 to 10 Year Old,Ready to move
4,Unnamed Property,"176 Cst Road, Kalina, Mumbai 400098, Santacruz...",3.5 Crore,"39,954",Carpet area: 876 (81.38 sq.m.),2,2,5th,5 to 10 Year Old,Ready to move
5,Varun Garden,"Manpada, Thane, Mumbai",2.2 Crore,"14,666",Super Built up area 1500(139.35 sq.m.)Carpet a...,3,3,7th,5 to 10 Year Old,Ready to move
6,Unnamed Property,V.P. Road Near Q Deck Family Restaurant And Ba...,1.65 Crore,"31,428",Built Up area: 525 (48.77 sq.m.),1,2,1st,1 to 5 Year Old,Ready to move
7,Unnamed Property,"Nahur East, Central Mumbai suburbs, Mumbai",1.4 Crore,"24,013",Carpet area: 583 (54.16 sq.m.),2,2,3rd,10+ Year Old,Ready to move
8,Unnamed Property,"Kalyan East, Mumbai Beyond Thane, Mumbai",65 Lac,"6,435",Super Built up area 1010(93.83 sq.m.),3,3,1st,5 to 10 Year Old,Ready to move
9,Sunteck West World,"701, 702, Naigaon East, Mira Road And Beyond, ...",86 Lac,"10,250",Carpet area: 788 (73.21 sq.m.),2,4,7th,0 to 1 Year Old,Ready to move

In [ ]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2581 entries, 0 to 2580
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Property_Name  2581 non-null   object
 1   Location       2581 non-null   object
 2   Price          2581 non-null   object
 3   Rate_SqFt      2581 non-null   object
 4   Area_Tpye      2581 non-null   object
 5   Bedroom        2581 non-null   int64
 6   Bathroom       2581 non-null   int64
 7   Floor_No       2581 non-null   object
 8   Property_Age   2581 non-null   object
 9   Availability   2581 non-null   object
dtypes: int64(2), object(8)
memory usage: 201.8+ KB

### 3. Data Preprocessing

#### 3.1 Remove the duplicates

In [ ]:
raw_data.drop_duplicates(inplace=True)

#### 3.1 Remove the Unwantend Symbols and Text

In [ ]:
raw_data["Property_Age"] = raw_data["Property_Age"].str.replace(' Old','')

In [ ]:
raw_data["Rate_SqFt"] = raw_data["Rate_SqFt"].str.replace(',','')

In [ ]:
raw_data["Availability"] = raw_data["Availability"].str.title()
raw_data["Availability"] = raw_data["Availability"].str.replace(' Property','')
raw_data["Availability"] = [i.lstrip() for i in raw_data["Availability"]]

In [ ]:
raw_data.Availability.unique()

array(['Ready To Move', 'Under Construction'], dtype=object)

#### 3.2 Set Colum Area in SqFt - added col

In [ ]:
area=[]
for i in range(2581):
    clean_sqft = re.sub('[^0-9.]', " ", raw_data["Area_Tpye"][i])
    area.append(clean_sqft.split()[0])
raw_data['Area_SqFt']=area

In [ ]:
raw_data.head(2)

,Property_Name,Location,Price,Rate_SqFt,Area_Tpye,Bedroom,Bathroom,Floor_No,Property_Age,Availability,Area_SqFt
0,Omkar Alta Monte,"W.E.Highway, Malad East, Mumbai",5 Crore,17241,Super Built up area 2900(269.42 sq.m.)Built Up...,3,4,14th,0 to 1 Year,Ready To Move,2900
1,T Bhimjyani Neelkanth Woods,"Manpada, Thane, Mumbai",2.4 Crore,12631,Super Built up area 1900(176.52 sq.m.)Built Up...,3,3,8th,1 to 5 Year,Ready To Move,1900

#### 3.3 Set Colum Type of Carpet Area

In [ ]:
carpet=[]
for i in range(2581):
    clean_carpet = re.sub('[^a-zA-Z]', " ", raw_data['Area_Tpye'][i])
    carpet.append(clean_carpet.split()[0]+' '+clean_carpet.split()[1])
raw_data['Area_Tpye']=carpet

In [ ]:
raw_data['Area_Tpye'] = raw_data.Area_Tpye.str.title()

In [ ]:
raw_data['Area_Tpye'] = raw_data.Area_Tpye.str.replace('Super Built','Super Built Up')
raw_data['Area_Tpye'] = raw_data.Area_Tpye.str.replace('Built Up','Built Up Area')
raw_data['Area_Tpye'] = raw_data.Area_Tpye.str.replace('Carpet Area ','Carpet Area')

In [ ]:
raw_data.Area_Tpye.unique()

array(['Super Built Up Area', 'Built Up Area', 'Carpet Area', 'Plot Area'],
      dtype=object)

In [ ]:
raw_data.head(2)

,Property_Name,Location,Price,Rate_SqFt,Area_Tpye,Bedroom,Bathroom,Floor_No,Property_Age,Availability,Area_SqFt
0,Omkar Alta Monte,"W.E.Highway, Malad East, Mumbai",5 Crore,17241,Super Built Up Area,3,4,14th,0 to 1 Year,Ready To Move,2900
1,T Bhimjyani Neelkanth Woods,"Manpada, Thane, Mumbai",2.4 Crore,12631,Super Built Up Area,3,3,8th,1 to 5 Year,Ready To Move,1900

#### 3.4 Remove Unwanted Text from Floor No

In [ ]:
raw_data['Floor_No'] = raw_data.Floor_No.str.replace('Ground','0')
raw_data['Floor_No'] = raw_data.Floor_No.str.replace('Basement','-1')

In [ ]:
floor=[]
for i in range(2581):
    clean_sqft = re.sub('[^0-9-]', "", raw_data["Floor_No"][i])
    floor.append(clean_sqft)
raw_data['Floor_No']=floor

In [ ]:
raw_data.head(2)

,Property_Name,Location,Price,Rate_SqFt,Area_Tpye,Bedroom,Bathroom,Floor_No,Property_Age,Availability,Area_SqFt
0,Omkar Alta Monte,"W.E.Highway, Malad East, Mumbai",5 Crore,17241,Super Built Up Area,3,4,14,0 to 1 Year,Ready To Move,2900
1,T Bhimjyani Neelkanth Woods,"Manpada, Thane, Mumbai",2.4 Crore,12631,Super Built Up Area,3,3,8,1 to 5 Year,Ready To Move,1900

#### 3.5 Set Colum Region

In [ ]:
raw_data["Location"] = [i.lstrip() for i in raw_data["Location"]]

In [ ]:
location=[]
for i in range(2581):
    clean_location = re.sub('[^a-zA-Z-]', " ", raw_data["Location"][i])
    location.append(clean_location)
raw_data['Region']=location

In [ ]:
raw_data['Region'] = raw_data.Region.str.title()
words = ['[0-9]','East','West','South','Suburbs','Sector','Beyond','And Beyond', 'Scheme']
raw_data["Region"] = raw_data["Region"].str.replace('|'.join(words), '', regex=True).str.strip()

In [ ]:
raw_data.head(2)

,Property_Name,Location,Price,Rate_SqFt,Area_Tpye,Bedroom,Bathroom,Floor_No,Property_Age,Availability,Area_SqFt,Region
0,Omkar Alta Monte,"W.E.Highway, Malad East, Mumbai",5 Crore,17241,Super Built Up Area,3,4,14,0 to 1 Year,Ready To Move,2900,W E Highway Malad Mumbai
1,T Bhimjyani Neelkanth Woods,"Manpada, Thane, Mumbai",2.4 Crore,12631,Super Built Up Area,3,3,8,1 to 5 Year,Ready To Move,1900,Manpada Thane Mumbai

In [ ]:
location=[]
for i in range(2581):
    try:
        location.append(raw_data['Region'][i].split()[-3]+' '+raw_data['Region'][i].split()[-2])
    except:
        location.append(raw_data['Region'][i].split()[-2]+' '+raw_data['Region'][i].split()[-1])
raw_data['Region']=location

In [ ]:
raw_data.head(2)

,Property_Name,Location,Price,Rate_SqFt,Area_Tpye,Bedroom,Bathroom,Floor_No,Property_Age,Availability,Area_SqFt,Region
0,Omkar Alta Monte,"W.E.Highway, Malad East, Mumbai",5 Crore,17241,Super Built Up Area,3,4,14,0 to 1 Year,Ready To Move,2900,Highway Malad
1,T Bhimjyani Neelkanth Woods,"Manpada, Thane, Mumbai",2.4 Crore,12631,Super Built Up Area,3,3,8,1 to 5 Year,Ready To Move,1900,Manpada Thane

In [ ]:
raw_data.Region.value_counts().head(30)

Region
Central Mumbai               226
Mira Road                    201
Kharghar Navi-Mumbai         196
Ulwe Navi-Mumbai             174
Mumbai Thane                 166
Mumbai Harbour               104
Dombivli Thane                82
Hiranandani-Estate Thane      79
Ghansoli Navi-Mumbai          76
Kamothe Navi-Mumbai           64
Panvel Navi-Mumbai            61
Road Thane                    47
Kandivali Mumbai              44
Manpada Thane                 42
Thane Thane                   41
Koparkhairane Navi-Mumbai     39
Parel Mumbai                  36
Malad Mumbai                  31
Taloja Navi-Mumbai            31
Naupada Thane                 30
Balkum Thane                  29
Vadavali Thane                29
Nagar Thane                   25
Dahisar Mumbai                24
Andheri Mumbai                24
Borivali Mumbai               23
Goregaon Mumbai               22
Thakur Village                21
Kalher Thane                  19
Roadpali Navi-Mumbai          18
Name: count, dtype: int64

In [ ]:
add=[]
for i in range(2581):
    clean_add = re.sub('[^a-zA-Z0-9]', " ", raw_data["Location"][i])
    add.append(clean_add)
raw_data['Location']=add

In [ ]:
raw_data["Location"] = raw_data["Location"].str.replace('   ',' ')
raw_data["Location"] = raw_data["Location"].str.replace('  ',' ')

In [ ]:
raw_data.head(2)

,Property_Name,Location,Price,Rate_SqFt,Area_Tpye,Bedroom,Bathroom,Floor_No,Property_Age,Availability,Area_SqFt,Region
0,Omkar Alta Monte,W E Highway Malad East Mumbai,5 Crore,17241,Super Built Up Area,3,4,14,0 to 1 Year,Ready To Move,2900,Highway Malad
1,T Bhimjyani Neelkanth Woods,Manpada Thane Mumbai,2.4 Crore,12631,Super Built Up Area,3,3,8,1 to 5 Year,Ready To Move,1900,Manpada Thane

#### 3.6 Replace the all Values in Lac's from Price Column

In [ ]:
def converter(x):
    if 'Lac' in x:
        return f"{(float(x.strip('Lac'))*1):,.1f}"
    elif 'Crore' in x:
        return f"{(float(x.strip('Crore'))*100):,.1f}"

raw_data['Price_Lakh'] = raw_data['Price'].apply(converter)
raw_data["Price_Lakh"] = raw_data["Price_Lakh"].str.replace(',','')

In [ ]:
raw_data.head(5)

,Property_Name,Location,Price,Rate_SqFt,Area_Tpye,Bedroom,Bathroom,Floor_No,Property_Age,Availability,Area_SqFt,Region,Price_Lakh
0,Omkar Alta Monte,W E Highway Malad East Mumbai,5 Crore,17241,Super Built Up Area,3,4,14,0 to 1 Year,Ready To Move,2900,Highway Malad,500.0
1,T Bhimjyani Neelkanth Woods,Manpada Thane Mumbai,2.4 Crore,12631,Super Built Up Area,3,3,8,1 to 5 Year,Ready To Move,1900,Manpada Thane,240.0
2,Legend 1 Pramila Nagar,Dahisar West Mumbai,95 Lac,15966,Super Built Up Area,1,2,3,10+ Year,Ready To Move,595,Dahisar Mumbai,95.0
3,Unnamed Property,Vidyavihar West Vidyavihar West Central Mumbai...,3.75 Crore,25862,Built Up Area,3,3,1,5 to 10 Year,Ready To Move,1450,Central Mumbai,375.0
4,Unnamed Property,176 Cst Road Kalina Mumbai 400098 Santacruz Ea...,3.5 Crore,39954,Carpet Area,2,2,5,5 to 10 Year,Ready To Move,876,Santacruz Mumbai,350.0

#### 3.7 Check The Null Values and Remove

In [ ]:
raw_data.isna().sum()

Property_Name    0
Location         0
Price            0
Rate_SqFt        0
Area_Tpye        0
Bedroom          0
Bathroom         0
Floor_No         0
Property_Age     0
Availability     0
Area_SqFt        0
Region           0
Price_Lakh       1
dtype: int64

In [ ]:
raw_data.dropna(inplace=True)
raw_data.reset_index(drop=True, inplace=True)

In [ ]:
raw_data = raw_data.to_csv('Property_Location.csv', index=False)

#### 3.8 Sort the all Columns

In [ ]:
raw_data = pd.read_csv('Property_Location.csv')

In [ ]:
raw_data = raw_data[['Property_Name','Location','Region','Property_Age','Availability','Area_Tpye','Area_SqFt','Rate_SqFt','Floor_No','Bedroom','Bathroom','Price_Lakh']]

#### 3.9 Create a Final Clean CSV File

In [ ]:
property_mumbai = raw_data.to_csv('Mumbai_Property.csv', index=False)

In [ ]:
property_mumbai = pd.read_csv('Mumbai_Property.csv')
property_mumbai

,Property_Name,Location,Region,Property_Age,Availability,Area_Tpye,Area_SqFt,Rate_SqFt,Floor_No,Bedroom,Bathroom,Price_Lakh
0,Omkar Alta Monte,W E Highway Malad East Mumbai,Highway Malad,0 to 1 Year,Ready To Move,Super Built Up Area,2900.0,17241,14,3,4,500.0
1,T Bhimjyani Neelkanth Woods,Manpada Thane Mumbai,Manpada Thane,1 to 5 Year,Ready To Move,Super Built Up Area,1900.0,12631,8,3,3,240.0
2,Legend 1 Pramila Nagar,Dahisar West Mumbai,Dahisar Mumbai,10+ Year,Ready To Move,Super Built Up Area,595.0,15966,3,1,2,95.0
3,Unnamed Property,Vidyavihar West Vidyavihar West Central Mumbai...,Central Mumbai,5 to 10 Year,Ready To Move,Built Up Area,1450.0,25862,1,3,3,375.0
4,Unnamed Property,176 Cst Road Kalina Mumbai 400098 Santacruz Ea...,Santacruz Mumbai,5 to 10 Year,Ready To Move,Carpet Area,876.0,39954,5,2,2,350.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2575,Shagun White Woods,Sector 23 Ulwe Navi Mumbai Mumbai,Ulwe Navi-Mumbai,1 to 5 Year,Ready To Move,Built Up Area,1180.0,10338,2,2,2,122.0
2576,Guru Anant,Sector 2 Ulwe Navi Mumbai Mumbai,Ulwe Navi-Mumbai,0 to 1 Year,Ready To Move,Built Up Area,1090.0,8073,11,2,2,88.0
2577,Balaji Mayuresh Delta,Ulwe Navi Mumbai Mumbai,Ulwe Navi-Mumbai,1 to 5 Year,Ready To Move,Built Up Area,1295.0,10579,6,2,2,137.0
2578,Balaji Mayuresh Delta,Ulwe Navi Mumbai Mumbai,Ulwe Navi-Mumbai,1 to 5 Year,Ready To Move,Built Up Area,1850.0,9243,6,3,3,171.0
2579,Gurukrupa Tulsi Heights,Ulwe Navi Mumbai Mumbai,Ulwe Navi-Mumbai,0 to 1 Year,Ready To Move,Built Up Area,1100.0,8636,4,2,2,95.0